[tool.poetry]
name = "useful-scripts"
version = "0.1.0"
description = ""
authors = ["n.vladimirov"]
readme = "README.md"
packages = []

[tool.poetry.dependencies]
python = "^3.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
